version: '3'
services:
  resources-api:
    image: 750796802028.dkr.ecr.us-east-2.amazonaws.com/acg.eks.bookstore.resource-api:latest
    ports:
      - "5000:5000"
    environment:
      DYNAMODB_TABLE: development-resources
      AWS_DEFAULT_REGION: us-east-2
      AWS_ACCESS_KEY_ID: <access-key-id-here>
      AWS_SECRET_ACCESS_KEY: <secret-access-key-here>
  inventory-api:
    image: 750796802028.dkr.ecr.us-east-2.amazonaws.com/acg.eks.bookstore.inventory-api:latest
    ports:
      - 5001:5001
    links:
      - resources-api
    environment:
      DYNAMODB_TABLE: development-inventory
      RESOURCE_API_ENDPOINT: http://resources-api:5000
      AWS_DEFAULT_REGION: us-east-2
      AWS_ACCESS_KEY_ID: <access-key-id-here>
      AWS_SECRET_ACCESS_KEY: <secret-access-key-here>
  proxy:
    image: nginx:stable-alpine
    ports: 
      - 80:80
    depends_on:
      - resources-api
      - inventory-api
      - front-end
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  front-end:
    image: 750796802028.dkr.ecr.us-east-2.amazonaws.com/acg.eks.bookstore.front-end:latest
    ports:
      - "5002:80"

  clients-api:
    image: 750796802028.dkr.ecr.us-east-2.amazonaws.com/acg.eks.bookstore.clients-api:latest
    ports: 
      - "5003:5003"
    environment:
      AWS_DEFAULT_REGION: us-east-2
      AWS_ACCESS_KEY_ID: <access-key-id-here>
      AWS_SECRET_ACCESS_KEY: <secret-access-key-here>

  renting-api:
    image: 750796802028.dkr.ecr.us-east-2.amazonaws.com/acg.eks.bookstore.renting-api:latest
    ports:
      - "5004:3000"
    environment:
      AWS_DEFAULT_REGION: us-east-2
      AWS_ACCESS_KEY_ID: <access-key-id-here>
      AWS_SECRET_ACCESS_KEY: <secret-access-key-here>
      DYNAMODB_TABLE: development-renting
      INVENTORY_API_ENDPOINT: http://inventory-api:5001
      CLIENTS_API_ENDPOINT: http://clients-api:5003
      RESOURCES_API_ENDPOINT: http://renting-api:5004