version: 0.2

env:
  variables:
    # K8S_DEPLOYMENT_NAME: resource-api-development-acg-resource-api
    # K8S_CONTAINER_NAME: acg-resource-api
    HELM_RELEASE_NAME: resource-api-development
    NAMESPACE: development
    ECR_REPO: 750796802028.dkr.ecr.us-east-2.amazonaws.com/bookstore.resources-api

phases:
  install: 
    commands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
      - chmod 700 get_helm.sh
      - ./get_helm.sh
  pre_build: 
    commands:
      - source `pwd`/version
      - COMMIT_ID_SHORT=`echo "${CODEBUILD_RESOLVED_SOURCE_VERSION}" | cut -c1-8`
      - TAG=`echo "${MAJOR}.${MINOR}.${COMMIT_ID_SHORT}"`
      - echo ${TAG}
      # - aws eks --region ${AWS_DEFAULT_REGION} update-kubeconfig --name eks-acg
      # - kubectl get nodes
  build: 
    commands:
      # - helm upgrade --install --namespace ${NAMESPACE} resource-api-development --set image.repository=${ECR_REPO} --set image.tag=${TAG} infra/helm-v2
      - ls 
  post_build: 
    commands:
      - echo Done
