# Default values for acg-renting-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mariomerco/renting-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5004
  name: renting-api-service

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
