version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - TAG=${ECR_URI}:${MAJOR}.${MINOR}.${CODEBUILD_BUILD_NUMBER}
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker build -t ${TAG} '--network=host' -f src/Dockerfile src
  post_build:
    commands:
      - docker push ${TAG}